name: dl_gpu
channels:
  - pytorch
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.7.1
  - astor=0.7.1
  - blas=1.0
  - c-ares=1.15.0
  - ca-certificates=2019.5.15
  - certifi=2019.3.9
  - cffi=1.12.3
  - cudatoolkit=10.0.130
  - cudnn=7.6.0
  - cupti=10.0.130
  - freetype=2.9.1
  - gast=0.2.2
  - grpcio=1.16.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - intel-openmp=2019.4
  - joblib=0.13.2
  - jpeg=9b
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.8.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - markdown=3.1.1
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mock=3.0.5
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1c
  - pillow=6.0.0
  - pip=19.1.1
  - protobuf=3.8.0
  - pycparser=2.19
  - python=3.6.7
  - pytorch=1.1.0
  - readline=7.0
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - tensorflow-gpu=1.13.1
  - termcolor=1.1.0
  - tk=8.6.8
  - torchvision=0.3.0
  - werkzeug=0.15.4
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - munch==2.3.2
    - pandas==0.24.2
    - pretrainedmodels==0.7.4
    - python-dateutil==2.8.0
    - pytz==2019.1
    - tqdm==4.32.1

